dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=facebook setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: VY3nSqUjY+dU6xo8PAXd34GJaU6HKehR7XUELYGZhY4pGYh8q1LlrImNaHoIiZuW7BXc/1d3IvVnSwhMfBtTxretLFUt66LwHDNfLjcOhamH0iGI65JctyjO5BXyPwcRYFcAJqXUwqjXbVgTFZIzVXuJY5rJkOd+i4ms13KE2CM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
